# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-05 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='auth_type',
            field=models.CharField(choices=[('psk', 'psk'), ('ssh', 'ssh')], default='psk', max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_id',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='auth_token',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
