# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('key_algorithm', models.CharField(max_length=80)),
                ('key_base64', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('key_comment', models.CharField(max_length=80, blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to='apps.Application')),
            ],
        ),
    ]
