# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_public_key_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_login',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
