# Generated by Django 2.2.15 on 2020-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_sum', models.CharField(max_length=40, unique=True)),
                ('until', models.DateTimeField(null=True)),
                ('duration', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'api_lock',
            },
        ),
    ]
