version: "3.9"

services:
  db:
    image: "postgres:15"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ".docker/db/postgres.conf:/etc/postgresql/postgres.conf:ro"
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    command: "-c config_file=/etc/postgresql/postgres.conf"

  web:
    build: .docker/web
    volumes:
      - ".:/code"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

volumes:
  postgres-data:
