# Generated by Django 5.2.17 on 2026-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_application_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_id',
            field=models.CharField(default=None, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='auth_token',
            field=models.CharField(default=None, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
