# Generated by Django 3.2.16 on 2022-10-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0009_servertype_and_attribute_definitions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change',
        ),
    ]
