# Generated by Django 3.2.18 on 2023-03-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0013_change_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changedelete',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='changedelete',
            name='commit',
        ),
        migrations.AlterUniqueTogether(
            name='changeupdate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='changeupdate',
            name='commit',
        ),
        migrations.DeleteModel(
            name='ChangeAdd',
        ),
        migrations.DeleteModel(
            name='ChangeDelete',
        ),
        migrations.DeleteModel(
            name='ChangeUpdate',
        ),
    ]
