# Generated by Django 3.2.23 on 2023-11-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0015_attribute_history_field'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE attribute DROP CONSTRAINT IF EXISTS attribute_target_servertype_id_check"
        ),
        # This is the same as before but without a check for type relation.
        migrations.RunSQL(
            "ALTER TABLE attribute ADD CONSTRAINT attribute_target_servertype_id_check "
            "CHECK((type IN ('domain', 'supernet', 'relation')) = (target_servertype_id IS NOT NULL OR type = 'relation'))"
        ),
    ]
