# Generated by Django 4.2.23 on 2025-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0019_drop_intern_ip_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertype',
            name='ip_addr_type',
            field=models.CharField(choices=[('null', 'null: intern_ip must be empty, no inet attributes'), ('host', 'host: intern_ip and inet must be an ip address and unique across all objects per attribute'), ('loadbalancer', 'loadbalancer: intern_ip and inet must be an ip address'), ('network', 'network: intern_ip and inet must be an ip network, not overlapping with same servertype')], max_length=32),
        ),
    ]
