# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0005_attribute_clone'),
    ]

    operations = [
        migrations.AddField(
            model_name='servertypeattribute',
            name='_consistent_via_attribute',
            field=models.ForeignKey(
                blank=True,
                db_column='consistent_via_attribute_id',
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='consistent_via_servertype_attributes',
                to='serverdb.Attribute',
            ),
        ),
    ]
