# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0005_attribute_clone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDateTimeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField()),
            ],
            options={
                'db_table': 'server_datetime_attribute',
            },
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('macaddr', 'macaddr'), ('domain', 'domain'), ('boolean', 'boolean'), ('inet', 'inet'), ('reverse', 'reverse'), ('number', 'number'), ('datetime', 'datetime'), ('string', 'string'), ('supernet', 'supernet'), ('relation', 'relation'), ('date', 'date')], max_length=32),
        ),
        migrations.AddField(
            model_name='serverdatetimeattribute',
            name='attribute',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='serverdb.Attribute'),
        ),
        migrations.AddField(
            model_name='serverdatetimeattribute',
            name='server',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='serverdb.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='serverdatetimeattribute',
            unique_together=set([('server', 'attribute', 'value')]),
        ),
        migrations.AlterIndexTogether(
            name='serverdatetimeattribute',
            index_together=set([('attribute', 'value')]),
        ),
    ]
