# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-18 12:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0006_datetime_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, validators=[
                django.core.validators.RegexValidator(
                    '\\A(\\*\\.)?([a-z0-9]+(\\.|-+))*[a-z0-9]+\\Z',
                    'Invalid hostname')]),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE server "
                "DROP CONSTRAINT server_hostname_check, "
                "ADD CONSTRAINT server_hostname_check "
                "CHECK (hostname::text ~ '\A(\*\.)?([a-z0-9]+(\.|-+))*[a-z0-9]+\Z'::text);"
            ),
            reverse_sql=(
                "ALTER TABLE server "
                "DROP CONSTRAINT server_hostname_check, "
                "ADD CONSTRAINT server_hostname_check "
                "CHECK (hostname::text ~ '\A(\*\.)?([a-z0-9]+[\.\-])*[a-z0-9]+\Z'::text);"
            )
        ),
    ]
