# Generated by Django 2.2.15 on 2020-10-08 09:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('serverdb', '0007_hostname_regex_hyphens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '\\A(\\*\\.)?([a-z0-9]+(\\.|-+))*[a-z0-9]+\\Z', 'Invalid hostname'
                    )
                ],
            ),
        ),
    ]
