# Generated by Django 3.2.11 on 2022-01-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('serverdb', '0008_hostname_length_254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(
                choices=[
                    ('string', 'string'),
                    ('boolean', 'boolean'),
                    ('relation', 'relation'),
                    ('reverse', 'reverse'),
                    ('number', 'number'),
                    ('inet', 'inet'),
                    ('macaddr', 'macaddr'),
                    ('date', 'date'),
                    ('datetime', 'datetime'),
                    ('supernet', 'supernet'),
                    ('domain', 'domain'),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='serverdatetimeattribute',
            name='attribute',
            field=models.ForeignKey(
                db_index=False,
                limit_choices_to={'type': 'datetime'},
                on_delete=django.db.models.deletion.CASCADE,
                to='serverdb.attribute',
            ),
        ),
        migrations.AlterField(
            model_name='servertype',
            name='ip_addr_type',
            field=models.CharField(
                choices=[
                    ('null', 'null: intern_ip must be empty, no inet attributes'),
                    ('host', 'host: intern_ip and inet must be an ip address and unique across all objects'),
                    ('loadbalancer', 'loadbalancer: intern_ip and inet must be an ip address'),
                    (
                        'network',
                        'network: intern_ip and inet must be an ip network, not overlapping with same servertype',
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
