# Generated by Django 3.2.16 on 2022-11-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0012_migrate_change_tables'),
    ]

    operations = [
        # Apparently Django doesn't support creating indexes on jsonb keys yet
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS 
                serverdb_change_change_json_hostname
            ON
                serverdb_change ((change_json->'hostname'))
            WHERE
                change_type in ('create', 'delete');
            """
        ),
    ]
