# Generated by Django 3.2.20 on 2024-02-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='inet_address_family',
            field=models.CharField(choices=[('ANY', 'Any'), ('IPV4', 'IPv4'), ('IPV6', 'IPv6')], default='ANY', max_length=5),
        ),
    ]
