# Generated by Django 3.2.23 on 2024-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='inet_address_family',
            field=models.CharField(blank=True, choices=[(None, 'none or any'), ('IPV4', 'IPv4'), ('IPV6', 'IPv6')], max_length=5),
        ),
    ]
