# Generated by Django 3.2.20 on 2023-12-06 15:08

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='supernet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('string', 'string'), ('boolean', 'boolean'), ('relation', 'relation'), ('reverse', 'reverse'), ('number', 'number'), ('inet', 'inet'), ('inet4', 'inet4'), ('inet6', 'inet6'), ('macaddr', 'macaddr'), ('date', 'date'), ('datetime', 'datetime'), ('supernet', 'supernet'), ('domain', 'domain')], max_length=32),
        ),
        migrations.CreateModel(
            name='ServerInet6Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', netfields.fields.InetAddressField(max_length=39)),
                ('attribute', models.ForeignKey(db_index=False, limit_choices_to={'type': 'inet6'}, on_delete=django.db.models.deletion.CASCADE, to='serverdb.attribute')),
                ('server', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='serverdb.server')),
            ],
            options={
                'db_table': 'server_inet6_attribute',
                'unique_together': {('server', 'attribute', 'value')},
                'index_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ServerInet4Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', netfields.fields.InetAddressField(max_length=39)),
                ('attribute', models.ForeignKey(db_index=False, limit_choices_to={'type': 'inet4'}, on_delete=django.db.models.deletion.CASCADE, to='serverdb.attribute')),
                ('server', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='serverdb.server')),
            ],
            options={
                'db_table': 'server_inet4_attribute',
                'unique_together': {('server', 'attribute', 'value')},
                'index_together': {('attribute', 'value')},
            },
        ),
    ]
