# Generated by Django 3.2.20 on 2024-02-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='inet_address_type',
            field=models.TextField(choices=[('ANY', 'Any'), ('IPV4', 'IPv4'), ('IPV6', 'IPv6')], default='ANY'),
        ),
    ]
