# Generated by Django 5.2.15 on 2026-06-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0023_attribute_multi_target_servertype'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serverbooleanattribute',
            new_name='server_bool_attribu_25fb6c_idx',
            old_fields=('attribute',),
        ),
        migrations.RenameIndex(
            model_name='serverdateattribute',
            new_name='server_date_attribu_12cbb2_idx',
            old_fields=('attribute', 'value'),
        ),
        migrations.RenameIndex(
            model_name='serverdatetimeattribute',
            new_name='server_date_attribu_f35d26_idx',
            old_fields=('attribute', 'value'),
        ),
        migrations.RenameIndex(
            model_name='serverinetattribute',
            new_name='server_inet_attribu_8feba2_idx',
            old_fields=('attribute', 'value'),
        ),
        migrations.RenameIndex(
            model_name='servermacaddressattribute',
            new_name='server_maca_attribu_1bcfb5_idx',
            old_fields=('attribute', 'value'),
        ),
        migrations.RenameIndex(
            model_name='servernumberattribute',
            new_name='server_numb_attribu_6223e1_idx',
            old_fields=('attribute', 'value'),
        ),
        migrations.RenameIndex(
            model_name='serverrelationattribute',
            new_name='server_rela_attribu_ecf9db_idx',
            old_fields=('attribute', 'value'),
        ),
        migrations.RenameIndex(
            model_name='serverstringattribute',
            new_name='server_stri_attribu_59edc4_idx',
            old_fields=('attribute', 'value'),
        ),
    ]
