# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-25 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0001_initial'),
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrolgroup',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='access_control_groups', to='serverdb.Attribute'),
        ),
    ]
