# Generated by Django 3.2.23 on 2023-11-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.TextField(verbose_name='record_type')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverdb.attribute')),
                ('servertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverdb.servertype')),
                ('source_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverdb.attribute')),
            ],
        ),
    ]
