# Generated by Django 3.2.23 on 2023-11-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
    ]

    operations = [

    ]
