# Generated by Django 3.2.23 on 2023-11-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
        ('powerdns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('SSHFP', 'SSHFP'), ('TXT', 'TXT'), ('MX', 'MX')], max_length=8)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverdb.attribute')),
                ('servertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverdb.servertype')),
                ('source_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverdb.attribute')),
            ],
        ),
    ]
