# Generated by Django 3.2.23 on 2023-11-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
        ('powerdns', '0002_auto_20231117_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsetting',
            name='source_value_special',
            field=models.CharField(choices=[('object_id', 'object_id'), ('hostname', 'hostname'), ('servertype', 'servertype'), ('intern_ip', 'intern_ip')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recordsetting',
            name='source_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverdb.attribute'),
        ),
        migrations.AddConstraint(
            model_name='recordsetting',
            constraint=models.CheckConstraint(check=models.Q(('source_value', None), ('source_value_special', None), _connector='OR'), name='only_one_source_value'),
        ),
    ]
