# Generated by Django 3.2.23 on 2023-11-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0016_optional_servertype_for_relation'),
        ('powerdns', '0003_auto_20231121_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('object_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('SSHFP', 'SSHFP'), ('TXT', 'TXT'), ('MX', 'MX'), ('PTR', 'PTR')], max_length=8)),
                ('content', models.CharField(max_length=500)),
                ('domain', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='recordsetting',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverdb.attribute'),
        ),
        migrations.AlterField(
            model_name='recordsetting',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('SSHFP', 'SSHFP'), ('TXT', 'TXT'), ('MX', 'MX'), ('PTR', 'PTR')], max_length=8),
        ),
        migrations.AlterField(
            model_name='recordsetting',
            name='source_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='serverdb.attribute'),
        ),
        migrations.AlterField(
            model_name='recordsetting',
            name='source_value_special',
            field=models.CharField(blank=True, choices=[('object_id', 'object_id'), ('hostname', 'hostname'), ('servertype', 'servertype'), ('intern_ip', 'intern_ip')], max_length=30, null=True),
        ),
    ]
