# Generated by Django 3.2.23 on 2023-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdns', '0004_auto_20231128_0846'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recordsetting',
            name='only_one_source_value',
        ),
        migrations.AlterField(
            model_name='recordsetting',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA'), ('SRV', 'SRV'), ('TXT', 'TXT')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='recordsetting',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_value__isnull', False), ('source_value_special__isnull', True)), models.Q(('source_value__isnull', True), ('source_value_special__isnull', False)), _connector='OR'), name='only_one_source_value'),
        ),
    ]
