# Generated by Django 3.2.23 on 2023-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdns', '0005_auto_20231201_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
