# Generated by Django 3.2.23 on 2024-01-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerdns', '0008_auto_20240104_0223'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='powerdns_records',
        ),
    ]
