# Generated by Django 3.2.23 on 2024-01-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverdb', '0017_alter_server_hostname'),
        ('powerdns', '0009_alter_record_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsetting',
            name='servertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverdb.servertype'),
        ),
    ]
