# Generated by Django 4.2.30 on 2026-06-12 14:08

from django.db import migrations, models
import serveradmin.graphite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('graphite', '0002_template_and_variation_name_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='params',
            field=models.TextField(blank=True, help_text='\n        Part of the URL after "?" to GET the graph or the value from\n        the Graphite.  It will be concatenated with the params for\n        the template and the variation.  Make sure it doesn\'t include\n        any character that doesn\'t allowed on URL\'s.  Also do not include "?"\n        and do not put "&" at the end.\n\n        The params can include variables inside curly brackets like\n        "{hostname}".\n        Variables can be any string attribute except multiple ones related to\n        the servers.  See Python String Formatting documentation [1] for other\n        formatting options.  The dots inside the values are replaced with\n        underscores in advance.  If you need to include a brace character in\n        the parameters, it can be escaped by doubling: \'{{ and }}\'.\n\n        Example params:\n\n            width=500&height=500\n\n        [1] https://docs.python.org/2/library/string.html#formatstrings\n        ', validators=[serveradmin.graphite.validators.validate_unique_uri_parameters]),
        ),
        migrations.AlterField(
            model_name='numeric',
            name='params',
            field=models.TextField(blank=True, help_text='Same as the params of the collections', validators=[serveradmin.graphite.validators.validate_unique_uri_parameters]),
        ),
        migrations.AlterField(
            model_name='template',
            name='params',
            field=models.TextField(blank=True, help_text='\n        Same as the params of the collections.\n        ', validators=[serveradmin.graphite.validators.validate_unique_uri_parameters]),
        ),
        migrations.AlterField(
            model_name='variation',
            name='params',
            field=models.TextField(blank=True, help_text='\n        Same as the params of the collections.\n        ', validators=[serveradmin.graphite.validators.validate_unique_uri_parameters]),
        ),
    ]
