# Generated by Django 5.2.16 on 2026-08-28 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0004_application_last_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLoggingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this rule immediately without losing its configured expiry.')),
                ('enabled_until', models.DateTimeField(help_text='Logging stops matching automatically after this time.')),
                ('note', models.TextField(blank=True, help_text='Reason for enabling logging, e.g. a ticket link.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logging_rules', to='apps.application')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_query_logging_rules', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logging_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'API'), ('servershell', 'Servershell')], max_length=16)),
                ('query_text', models.TextField()),
                ('filters', models.JSONField(blank=True, null=True)),
                ('restrict', models.JSONField(blank=True, null=True)),
                ('order_by', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.FloatField()),
                ('num_results', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='apps.application')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='querylog.queryloggingrule')),
            ],
        ),
        migrations.AddIndex(
            model_name='queryloggingrule',
            index=models.Index(fields=['is_active', 'enabled_until'], name='querylog_qu_is_acti_acce8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='queryloggingrule',
            constraint=models.CheckConstraint(condition=models.Q(('application__isnull', False), ('user__isnull', False), _connector='OR'), name='querylog_rule_application_or_user_required'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['source', 'created_at'], name='querylog_qu_source_714e77_idx'),
        ),
    ]
