# Generated by Django 5.2.17 on 2026-10-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_application_last_login'),
        ('querylog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='apps.application'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='querylog.queryloggingrule'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queryloggingrule',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logging_rules', to='apps.application'),
        ),
        migrations.AlterField(
            model_name='queryloggingrule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logging_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
