# Generated by Django 5.2.16 on 2026-08-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querylog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryloggingrule',
            name='trigger_query',
            field=models.CharField(blank=True, help_text='Optional. Only log a query if its filters satisfy this condition, e.g. "hostname=Regexp(\'web.*\') environment=prod". Leave blank to log every query matched by application/user above. Use attr=All() to match any query that references "attr" at all, regardless of its value.', max_length=1000),
        ),
    ]
