# Generated by Django 5.2.16 on 2026-08-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querylog', '0002_queryloggingrule_trigger_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryloggingrule',
            name='trigger_attributes',
            field=models.JSONField(blank=True, default=list, help_text='Optional. Only log a query if its "restrict" (the list of attributes it asked to have returned) includes at least one of the attributes selected here. Leave empty to log every query matched by application/user/trigger_query above. Includes the special attributes object_id, hostname, servertype and intern_ip, which are not real serverdb attributes but are valid values for "restrict".'),
        ),
    ]
