# Generated by Django 4.2.23 on 2025-09-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serverdb', '0021_serverinetattribute_server_inet_attribute_value_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('attributes', models.ManyToManyField(to='serverdb.attribute')),
            ],
        ),
    ]
