# Generated by Django 2.2.15 on 2020-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashsum', models.CharField(max_length=40)),
                ('until', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'api_lock',
            },
        ),
    ]
