# Generated by Django 5.2.17 on 2026-09-18 05:01

import django.db.models.deletion
import django.utils.timezone
import serveradmin.serverdb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serverdb', '0025_rename_serverbooleanattribute_attribute_server_bool_attribu_25fb6c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=serveradmin.serverdb.models.Change.ChangeJSONEncoder)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_by', models.CharField(blank=True, default='', max_length=128)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, encoder=serveradmin.serverdb.models.Change.ChangeJSONEncoder, null=True)),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='serverdb.changecommit')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['state', 'task_type', 'run_after', 'id'], name='taskqueue_task_claim_idx'), models.Index(fields=['state', 'locked_until'], name='taskqueue_task_lease_idx'), models.Index(fields=['state', 'finished_at'], name='taskqueue_task_prune_idx')],
            },
        ),
    ]
